### ISSUE TITLE
Failed to activate the open-unsupported-files package

### ISSUE THREAD

**Issue by JackJennings304** [skandasoft/open-unsupported-files#15]
[Enter steps to reproduce:]

1. Copied package to my install directory.
2. Got this error when I started Atom.   Google search showed [skandasoft](https://github.com/atom/atom/issues/9402) submitted issue but I saw no resolution.

Any ideas?

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [open-unsupported-files](https://github.com/skandasoft/open-unsupported-files) package 1.0.20

### Stack Trace

Failed to activate the open-unsupported-files package

```
At Cannot find module 'atom-utils'

Error: Cannot find module 'atom-utils'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.18.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.18.0/resources/app/src/module-cache.js:354:58)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:66:33)
    at Object.activate (/packages/open-unsupported-files-master/lib/open-unsupported-files.coffee:10:25)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:253:25)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.18.0/resources/app/src/package-manager.js:645:40)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.18.0/resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (~/AppData/Local/atom/app-1.18.0/resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (~/AppData/Local/atom/app-1.18.0/resources/app/src/package-manager.js:603:52)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/atom-environment.js:846:34
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.30.3 
atom-overtype-mode 0.3.4 
Sublime-Style-Column-Selection 1.7.4 
open-unsupported-files 1.0.20 
project-manager 3.3.5 
```

**Comment by weslo** [comment]
Did you install via atom package manager or did you clone the repo and copy the files into atom's packages directory manually? I forget exactly what this project depends on but you might need to have atom install dependencies or you might need to npm install in the package if you copied it over. I am not experiencing this issue on the same version of atom as you.

**Comment by JackJennings304** [comment]
Ok.  I'll try that.

**Comment by JackJennings304** [comment]
Tried your advice.  It worked!  Thanks!

**Comment by weslo** [comment]
@JackJennings304 Glad I could help!

**Comment by weslo** [comment]
@skandasoft This issue can be closed!
